# Generated by Django 4.1.2 on 2022-10-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='short_url',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
    ]
